server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://74.249.8.84:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/tasks/**
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/candidates/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
