server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  instance:
    hostname: 74.249.8.84
    prefer-ip-address: true
    ip-address: 74.249.8.84
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://74.249.8.84:${server.port}/eureka/
  server:
    enableSelfPreservation: false
