spring:
  application:
    name: user-service
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB          # Maximum size for individual file uploads
      max-request-size: 100MB      # Maximum request size (for multiple file uploads)

  # File storage properties
  file:
    upload-dir: src/main/resources/static/images # Directory to save uploaded files

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456789
    key-store-type: PKCS12
    key-alias: kamdem

